// @generated
// This file is autogenerated, do not edit manually

/** [See route renderer](./Editor_route_renderer.res)*/
module Editor = {
  module Route = Route__Editor_route

  /** [See route renderer](./Editor__Source_route_renderer.res)*/
  module Source = {
    module Route = Route__Editor__Source_route

  }
}
/** [See route renderer](./Profile_route_renderer.res)*/
module Profile = {
  module Route = Route__Profile_route

}
/** [See route renderer](./Explore_route_renderer.res)*/
module Explore = {
  module Route = Route__Explore_route

}
/** [See route renderer](./Invite_route_renderer.res)*/
module Invite = {
  module Route = Route__Invite_route

}
/** [See route renderer](./NotFound_route_renderer.res)*/
module NotFound = {
  module Route = Route__NotFound_route

}