#!/usr/bin/env node
import {createHash, randomBytes} from "node:crypto";
import {execFileSync, spawnSync} from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import {createServer} from "node:net";
import {basename, dirname, resolve} from "node:path";
import {fileURLToPath} from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envLocalPath = resolve(root, ".env.local");
const secretsEnvPath = resolve(root, ".env.secrets.local");
const localnetEnvPath = resolve(root, ".localnet.env");
const lockPath = resolve(root, ".gen-env.lock");
const kubeDir = resolve(root, ".k8s");
const kubeconfigPath = resolve(kubeDir, "kubeconfig");
const ctlptlDir = resolve(root, ".ctlptl");
const generatedMarker = "# Generated by scripts/localnet-gen-env.js - DO NOT EDIT";

const portSpecs = [
  ["HTTP_PORT", 4555],
  ["FRONTEND_PORT", 5177],
  ["POSTGRES_PORT", 5432],
  ["TILT_PORT", 10350],
  ["K3D_REGISTRY_PORT", 5055],
];

function printHelp() {
  console.log(`localnet-gen-env - Generate Vibespace local Kubernetes environment

Usage:
  node scripts/localnet-gen-env.js              Create localnet environment
  node scripts/localnet-gen-env.js --random     Allocate random free ports
  node scripts/localnet-gen-env.js --force      Clean existing generated env first
  node scripts/localnet-gen-env.js --clean      Delete generated cluster/env
  node scripts/localnet-gen-env.js --status     Show current generated env

Options:
  --random   Use random free ports instead of preferring defaults
  --force    Clean generated env before recreating
  --clean    Delete the generated k3d cluster and local env files
  --yes      Do not prompt before --clean
  --status   Print localnet status
  -h, --help Show this help`);
}

function parseArgs(argv) {
  const parsed = {
    clean: false,
    force: false,
    help: false,
    random: false,
    status: false,
    yes: false,
  };

  for (const arg of argv) {
    switch (arg) {
      case "--clean":
        parsed.clean = true;
        break;
      case "--force":
        parsed.force = true;
        break;
      case "--random":
        parsed.random = true;
        break;
      case "--status":
        parsed.status = true;
        break;
      case "--yes":
        parsed.yes = true;
        break;
      case "-h":
      case "--help":
        parsed.help = true;
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return parsed;
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: root,
    encoding: "utf8",
    stdio: options.stdio ?? "inherit",
    input: options.input,
    env: options.env ?? process.env,
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed with exit code ${result.status}`);
  }

  return result.stdout ?? "";
}

function capture(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: root,
    encoding: "utf8",
    stdio: ["ignore", "pipe", options.stderr ?? "ignore"],
    env: options.env ?? process.env,
  }).trim();
}

function commandExists(command) {
  try {
    capture("sh", ["-lc", `command -v ${command}`]);
    return true;
  } catch {
    return false;
  }
}

function requireTool(command) {
  if (!commandExists(command)) {
    throw new Error(`${command} is required. Enter the Nix shell with \`direnv allow\` or \`nix develop\`, then retry.`);
  }
}

function sanitizeName(raw) {
  const sanitized = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+/, "")
    .replace(/-+$/, "");

  return sanitized || "vibespace";
}

function shortHash(value) {
  return createHash("sha1").update(value).digest("hex").slice(0, 6);
}

function truncateMiddle(value, maxLength) {
  if (value.length <= maxLength) {
    return value;
  }

  const hash = shortHash(value);
  return `${value.slice(0, maxLength - hash.length - 1)}-${hash}`;
}

function gitRoot() {
  try {
    return capture("git", ["rev-parse", "--show-toplevel"]);
  } catch {
    return root;
  }
}

function localIdentity() {
  const repoRoot = gitRoot();
  const worktree = sanitizeName(basename(repoRoot));
  const hash = shortHash(repoRoot);
  const cluster = truncateMiddle(`vs-${worktree}-${hash}`, 28);
  const registryHost = `${cluster}-registry.localhost`;

  return {
    cluster,
    context: `k3d-${cluster}`,
    namespace: cluster,
    registryHost,
    worktree,
  };
}

function readEnvFile(filePath) {
  if (!existsSync(filePath)) {
    return {};
  }

  const env = {};
  const text = readFileSync(filePath, "utf8");
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || !line.includes("=")) {
      continue;
    }

    const [key, ...rest] = line.replace(/^export\s+/, "").split("=");
    let value = rest.join("=");
    if (
      (value.startsWith("\"") && value.endsWith("\"")) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function formatEnvLine(key, value) {
  const text = String(value ?? "");
  if (/[ \t"'`$\\]/.test(text)) {
    return `${key}="${text.replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"`;
  }
  return `${key}=${text}`;
}

function isGeneratedEnv(filePath) {
  return existsSync(filePath) && readFileSync(filePath, "utf8").includes(generatedMarker);
}

function backupUngeneratedEnv() {
  if (!existsSync(envLocalPath) || isGeneratedEnv(envLocalPath)) {
    return;
  }

  const backupPath = resolve(root, `.env.local.before-vibespace-localnet-${Date.now()}`);
  copyFileSync(envLocalPath, backupPath);
  console.log(`Backed up existing .env.local to ${basename(backupPath)}`);
}

function localSecretEnv() {
  return {
    ...readEnvFile(secretsEnvPath),
    ...process.env,
  };
}

function randomSecret(byteLength = 32) {
  return randomBytes(byteLength).toString("base64url");
}

function generatedFrontendEnv() {
  const secrets = localSecretEnv();
  return {
    VITE_SEND_SUPABASE_URL: secrets.VITE_SEND_SUPABASE_URL || secrets.SEND_SUPABASE_URL || "",
    VITE_SEND_SUPABASE_ANON_KEY: secrets.VITE_SEND_SUPABASE_ANON_KEY || secrets.SEND_SUPABASE_ANON_KEY || "",
  };
}

function localGraphqlEndpoint(ports) {
  return `http://127.0.0.1:${ports.HTTP_PORT}/graphql`;
}

function readLock() {
  if (!existsSync(lockPath)) {
    return null;
  }

  return JSON.parse(readFileSync(lockPath, "utf8"));
}

function writeLock(lock) {
  writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`);
}

async function isPortFree(port, host) {
  return new Promise((resolvePort) => {
    const server = createServer();
    const timeout = setTimeout(() => {
      server.close();
      resolvePort(false);
    }, 100);

    server.once("error", (error) => {
      clearTimeout(timeout);
      resolvePort(error.code === "EADDRNOTAVAIL" || error.code === "EINVAL");
    });

    server.listen(port, host, () => {
      clearTimeout(timeout);
      server.close(() => resolvePort(true));
    });
  });
}

async function canBindPort(port) {
  return (await isPortFree(port, "127.0.0.1")) && (await isPortFree(port, "0.0.0.0"));
}

function randomPortCandidate() {
  return 10000 + Math.floor(Math.random() * 22768);
}

async function pickPort(defaultPort, used, preferDefault) {
  if (preferDefault && !used.has(defaultPort) && (await canBindPort(defaultPort))) {
    used.add(defaultPort);
    return defaultPort;
  }

  for (let attempt = 0; attempt < 100; attempt++) {
    const candidate = randomPortCandidate();
    if (!used.has(candidate) && (await canBindPort(candidate))) {
      used.add(candidate);
      return candidate;
    }
  }

  throw new Error("Failed to allocate a free local port");
}

async function allocatePorts({random}) {
  const used = new Set();
  const ports = {};

  for (const [key, defaultPort] of portSpecs) {
    ports[key] = String(await pickPort(defaultPort, used, !random));
  }

  return ports;
}

function ensureTools() {
  requireTool("docker");
  requireTool("k3d");
  requireTool("kubectl");

  try {
    run("docker", ["info"], {stdio: "ignore"});
  } catch {
    throw new Error("Docker is installed but not reachable. Start Docker, then retry.");
  }
}

function clusterExists(cluster) {
  try {
    capture("k3d", ["cluster", "get", cluster]);
    return true;
  } catch {
    return false;
  }
}

function createOrReuseCluster(identity, ports) {
  const registryRef = `${identity.registryHost}:${ports.K3D_REGISTRY_PORT}`;

  if (clusterExists(identity.cluster)) {
    console.log(`Using existing k3d cluster: ${identity.cluster}`);
  } else {
    console.log(`Creating k3d cluster: ${identity.cluster}`);
    run("k3d", [
      "cluster",
      "create",
      identity.cluster,
      "--agents",
      "1",
      "--registry-create",
      registryRef,
      "--kubeconfig-update-default=false",
      "--kubeconfig-switch-context=false",
      "--wait",
    ]);
  }

  mkdirSync(kubeDir, {recursive: true});
  const kubeconfig = capture("k3d", ["kubeconfig", "get", identity.cluster], {stderr: "pipe"});
  writeFileSync(kubeconfigPath, `${kubeconfig}\n`);

  const env = {...process.env, KUBECONFIG: kubeconfigPath};
  const namespaceYaml = run(
    "kubectl",
    ["--kubeconfig", kubeconfigPath, "create", "namespace", identity.namespace, "--dry-run=client", "-o", "yaml"],
    {stdio: ["ignore", "pipe", "inherit"], env},
  );
  run("kubectl", ["--kubeconfig", kubeconfigPath, "apply", "-f", "-"], {
    input: namespaceYaml,
    stdio: ["pipe", "inherit", "inherit"],
    env,
  });
}

function writeEnvFiles(identity, ports, frontendEnv) {
  const secrets = localSecretEnv();
  const registryUrl = `${identity.registryHost}:${ports.K3D_REGISTRY_PORT}`;
  const registryInternalUrl = `k3d-${identity.registryHost}:5000`;
  const graphqlEndpoint = localGraphqlEndpoint(ports);
  const generatedAt = new Date().toISOString();

  const env = {
    ...frontendEnv,
    VIBESPACE_ENV: "localnet",
    WORKTREE_NAME: identity.worktree,
    KUBECONFIG: kubeconfigPath,
    K8S_CONTEXT: identity.context,
    K8S_NAMESPACE: identity.namespace,
    K3D_CLUSTER: identity.cluster,
    K3D_REGISTRY_NAME: registryUrl,
    K3D_REGISTRY_PORT: ports.K3D_REGISTRY_PORT,
    REGISTRY_URL: registryUrl,
    REGISTRY_INTERNAL_URL: registryInternalUrl,
    HTTP_PORT: ports.HTTP_PORT,
    FRONTEND_PORT: ports.FRONTEND_PORT,
    VIBESPACE_GRAPHQL_PUBLIC_URL: graphqlEndpoint,
    VIBESPACE_SESSION_SECRET: secrets.VIBESPACE_SESSION_SECRET || randomSecret(32),
    VIBESPACE_DEV_ADMIN_TOKEN: secrets.VIBESPACE_DEV_ADMIN_TOKEN || randomSecret(24),
    VITE_GRAPHQL_ENDPOINT: graphqlEndpoint,
    POSTGRES_PORT: ports.POSTGRES_PORT,
    POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD || "vibespace",
    TILT_PORT: ports.TILT_PORT,
  };

  const lines = [
    generatedMarker,
    `# Generated: ${generatedAt}`,
    "",
    "# Local secrets live in .env.secrets.local or .envrc.private and are not copied into this generated file.",
    ...Object.entries(env).map(([key, value]) => formatEnvLine(key, value)),
    "",
  ];

  const content = lines.join("\n");
  writeFileSync(envLocalPath, content);
  writeFileSync(localnetEnvPath, content);

  writeLock({
    version: 1,
    generatedAt,
    clusterName: identity.cluster,
    context: identity.context,
    envFile: ".env.local",
    kubeconfigPath,
    namespace: identity.namespace,
    registryUrl,
    registryInternalUrl,
  });
}

function cleanGeneratedEnv({yes}) {
  const lock = readLock();
  const cluster = lock?.clusterName;

  if (!yes) {
    throw new Error("Refusing to clean without --yes");
  }

  if (cluster) {
    ensureTools();
    if (clusterExists(cluster)) {
      console.log(`Deleting k3d cluster: ${cluster}`);
      run("k3d", ["cluster", "delete", cluster]);
    }
  }

  for (const filePath of [envLocalPath, localnetEnvPath, lockPath]) {
    if (existsSync(filePath) && (filePath !== envLocalPath || isGeneratedEnv(filePath))) {
      rmSync(filePath, {force: true});
    }
  }

  for (const dirPath of [kubeDir, ctlptlDir]) {
    if (existsSync(dirPath)) {
      rmSync(dirPath, {force: true, recursive: true});
    }
  }
}

function printStatus() {
  const lock = readLock();
  if (!lock) {
    console.log("No generated Vibespace localnet environment exists.");
    return;
  }

  console.log(`cluster=${lock.clusterName}`);
  console.log(`context=${lock.context}`);
  console.log(`namespace=${lock.namespace}`);
  console.log(`kubeconfig=${lock.kubeconfigPath}`);
  console.log(`registry=${lock.registryUrl}`);
  console.log(`generatedAt=${lock.generatedAt}`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    printHelp();
    return;
  }

  if (args.status) {
    printStatus();
    return;
  }

  if (args.clean) {
    cleanGeneratedEnv({yes: args.yes});
    return;
  }

  const frontendEnv = generatedFrontendEnv();

  ensureTools();

  const lock = readLock();
  if (lock) {
    if (!args.force) {
      throw new Error("Generated localnet already exists. Run with --force or clean with --clean --yes.");
    }
    cleanGeneratedEnv({yes: true});
  }

  if (existsSync(envLocalPath) && !isGeneratedEnv(envLocalPath)) {
    if (!args.force) {
      throw new Error("Existing .env.local is not generated by Vibespace. Move secrets to .env.secrets.local or .envrc.private, or rerun with --force to back it up.");
    }
    backupUngeneratedEnv();
  }

  const identity = localIdentity();
  const ports = await allocatePorts({random: args.random});
  createOrReuseCluster(identity, ports);
  writeEnvFiles(identity, ports, frontendEnv);

  console.log("Generated Vibespace localnet environment.");
  console.log(`  env: .env.local`);
  console.log(`  cluster: ${identity.cluster}`);
  console.log(`  kubeconfig: .k8s/kubeconfig`);
  console.log(`  tilt: http://127.0.0.1:${ports.TILT_PORT}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
